export const imgUrl = 'https://bishworang.wavebox.net/assets/images/setting/'
export const catImg = 'https://bishworang.wavebox.net/assets/images/category/'
export const sliderImg = 'https://bishworang.wavebox.net/assets/images/slider/'
export const productImg = 'https://bishworang.wavebox.net/assets/images/product/'
export const bannerImg = 'https://bishworang.wavebox.net/assets/images/banner/'
export const testimonialImg = 'https://bishworang.wavebox.net/assets/images/testimonials/'
export const profileImg = 'https://bishworang.wavebox.net/assets/images/img/'